# Generated by Django 4.1.6 on 2023-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.JSONField(default=list)),
                ('total_present', models.IntegerField()),
                ('absentee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=9)),
                ('roll_no', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=3)),
                ('dept', models.CharField(max_length=9)),
            ],
        ),
    ]
