# Generated by Django 4.1.6 on 2023-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance',
            field=models.JSONField(default=set),
        ),
    ]
